// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type FileChange struct {
	ID        int64  `json:"id"`
	SessionID int64  `json:"session_id"`
	FilePath  string `json:"file_path"`
	ToolName  string `json:"tool_name"`
	Added     int64  `json:"added"`
	Removed   int64  `json:"removed"`
	CreatedAt string `json:"created_at"`
}

type Session struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	Model     string `json:"model"`
	Mode      string `json:"mode"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SessionMessage struct {
	ID        int64  `json:"id"`
	SessionID int64  `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	ToolName  string `json:"tool_name"`
	ToolArgs  string `json:"tool_args"`
	IsError   int64  `json:"is_error"`
	Thinking  string `json:"thinking"`
	CreatedAt string `json:"created_at"`
}

type TokenStat struct {
	ID           int64  `json:"id"`
	SessionID    int64  `json:"session_id"`
	Turn         int64  `json:"turn"`
	EvalCount    int64  `json:"eval_count"`
	PromptTokens int64  `json:"prompt_tokens"`
	Model        string `json:"model"`
	CreatedAt    string `json:"created_at"`
}

type ToolPermission struct {
	ID        int64  `json:"id"`
	ToolName  string `json:"tool_name"`
	Policy    string `json:"policy"`
	UpdatedAt string `json:"updated_at"`
}
